######################################################################
# Automatically generated by qmake (2.01a) Tue Oct 22 11:37:34 2013
######################################################################

TEMPLATE = app
TARGET = ringerei
DEPENDPATH += . src
INCLUDEPATH += . include
INCLUDEPATH += /usr/include/cryptopp/
INCLUDEPATH += /usr/include/ring/
QMAKE_LIBDIR += /usr/lib/
LIBS += -lring
LIBS += -lcrypto++
OBJECTS_DIR = obj

# Input
SOURCES += src/ringerei.cpp
